name: Test
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - '17.x'
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install pnpm
        run: npm install -g pnpm@latest
      
      - name: Cache dependencies 🛖
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
            ~/.cache
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install dependencies 📥
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --fix-lockfile

      - name: Install Cypress 📥
        if: steps.cache.outputs.cache-hit != 'true'
        run: npx cypress install

      - name: Build 🚚
        run: npm run build

      - name: test 🧪
        run: npm test

          
